// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApprovalController from "./approval_controller"
application.register("approval", ApprovalController)

import MapController from "./map_controller"
application.register("map", MapController)
